USE [master]
GO

/****** Object:  Database [JLBSampleDB]    Script Date: 6/7/2017 4:41:18 PM ******/

/****** NOTE: Modify database and transaction log file locations for your envirnoment. ******/

CREATE DATABASE [JLBSampleDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'JLBSampleDB', FILENAME = N'U:\SQLData\Data\JLBSampleDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'JLBSampleDB_log', FILENAME = N'U:\SQLData\Logs\JLBSampleDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [JLBSampleDB] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [JLBSampleDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [JLBSampleDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [JLBSampleDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [JLBSampleDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [JLBSampleDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [JLBSampleDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [JLBSampleDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [JLBSampleDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [JLBSampleDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [JLBSampleDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [JLBSampleDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [JLBSampleDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [JLBSampleDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [JLBSampleDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [JLBSampleDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [JLBSampleDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [JLBSampleDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [JLBSampleDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [JLBSampleDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [JLBSampleDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [JLBSampleDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [JLBSampleDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [JLBSampleDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [JLBSampleDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [JLBSampleDB] SET  MULTI_USER 
GO

ALTER DATABASE [JLBSampleDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [JLBSampleDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [JLBSampleDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [JLBSampleDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [JLBSampleDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [JLBSampleDB] SET QUERY_STORE = OFF
GO

USE [JLBSampleDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [JLBSampleDB] SET  READ_WRITE 
GO


